### PR TITLE
[JBPM-9711] JbpmJUnitBaseTestCase no longer uses default datasource properties

### PR DESCRIPTION
**Pull request by afalhambra**
**[JBPM-9711](https://issues.redhat.com/browse/JBPM-9711)**: JbpmJUnitBaseTestCase no longer uses default datasource properties

depends on https://github.com/kiegroup/jbpm/pull/1923

### CODE REVIEW

**Comment by afalhambra** [comment]
@gmunozfe can you please have a review? thanks!

**Comment by gmunozfe** [comment]
jenkins test this

**Review by gmunozfe — APPROVED** [review]
Looks good to me, perfectly done @afalhambra !

**Comment by afalhambra** [comment]
@mareknovotny please merge, thanks

**Pull request merged**
