### PR TITLE
[KOGITO-3222] Implement jpmml/trustypmml co-existence

### PR DESCRIPTION
**Pull request by gitgabrio**
This PR depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1451

@danielezonca @tarilabs  @jiripetrlik

See https://issues.redhat.com/browse/KOGITO-3222

This PR add Jandex indexing to kie-dmn-jpmml

### CODE REVIEW

**Comment by gitgabrio** [comment]
jenkins please retest this

**Comment by Ginxo** [comment]
jenkins please retest this

**Comment by Ginxo** [comment]
jenkins please retest this

**Comment by Ginxo** [comment]
jenkins please retest this

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
